services:
  php:
    image: yiisoftware/yii2-php:8.2-fpm-nginx
    container_name: ${APP_NAME}-php
    environment:
      PG_DSN:
      PG_USER:
      PG_PASSWORD:
    volumes:
      - ./:/app:delegated
      # Конфиг PHP
      - ./docker/php/extras.ini:/usr/local/etc/php/php.ini:ro
      # Конфиг Nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - '${APP_PORT}:80'

  postgres:
    image: postgres:17
    container_name: ${APP_NAME}-postgres
    ports:
      - "${PG_EXTERNAL_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: "${PG_ROOT_PASSWORD}"
      PG_USER: "${PG_USER}"
      PG_PASSWORD: "${PG_PASSWORD}"
      PG_DBNAME: "${PG_DBNAME}"

volumes:
  pgdata: