#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $PG_USER with password '$PG_PASSWORD';
    ALTER ROLE $PG_USER WITH LOGIN;
    CREATE DATABASE $PG_DBNAME OWNER $PG_USER;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    GRANT ALL ON SCHEMA public TO $PG_USER;
    GRANT ALL PRIVILEGES ON DATABASE $PG_DBNAME TO $PG_USER;
EOSQL
